name: Docker Image CD

on:
  workflow_dispatch:  # manual trigger
  schedule:
      # ┌───────────── minute (0 - 59)
      # │ ┌───────────── hour (0 - 23)
      # │ │ ┌───────────── day of the month (1 - 31)
      # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
      # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
      # │ │ │ │ │
      # │ │ │ │ │
      # │ │ │ │ │
      # * * * * *
    - cron: '0 0 * * 1'  # build every Monday
  push:
    branches: [ master ]
    tags:
      - '*.*'
      - '*.*.*'
  pull_request:
    branches: [ master ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: mingc/latex
        labels: |
          org.opencontainers.image.url=https://hub.docker.com/r/mingc/latex
          org.opencontainers.image.vendor=Ming Chen

    - name: Pre build
      run: |
        uname -a
        df -h
        docker images
        echo "GITHUB_SHA: $GITHUB_SHA"

        # Remove exist images to free disk space
        docker image prune -a -f
        #docker rmi $(docker images | grep -v IMAGE | awk '{print $3}')
        docker images

        # check disk space one more time
        df -h

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: amd64,arm64,arm,mips64,mips64le,riscv64,s390x,

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      # if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        #platforms: linux/amd64,linux/arm64,linux/riscv64,linux/arm/v7,linux/s390x
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        # push: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: mingc/latex:latest,${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
