import mongoose from 'mongoose';

export type Job = mongoose.Document & {
  id: string,
  userId: string,
  company: string,
  position: string,
  status: string,
  website: string,
  resumeLink: string,
  hunterData: object,
  coverLetterLink: string,
  coverLetter: {
    url: string,
    status: string,
    dateGenerated: Date
  },
  jobDescription: string,
  notes: string,
  contactName: string,
  contactEmail: string,
  contactPhone: string,
  interviewDate: Date,
  salary: number,
  location: string,
  remoteType: string,
  jobType: string,
  dateCreated: Date,
  dateUpdated: Date,
  dateApplied: Date,
  flag: string,
  isArchived: boolean,
  aiRated: boolean,
  aiNotes: string,
  aiRating: number,
};

const JobSchema = new mongoose.Schema({
  id: String,
  userId: String,
  company: String,
  position: String,
  status: String,
  website: String,
  resumeLink: String,
  hunterData: Object,
  coverLetterLink: String,
  coverLetter: {
    url: String,
    status: String,
    dateGenerated: Date
  },
  jobDescription: String,
  notes: String,
  contactName: String,
  contactEmail: String,
  contactPhone: String,
  interviewDate: Date,
  salary: Number,
  location: String,
  remoteType: String,
  jobType: String,
  dateCreated: Date,
  dateUpdated: Date,
  dateApplied: Date,
  flag: String,
  isArchived: Boolean,
  aiRated: Boolean,
  aiNotes: String,
  aiRating: Number,
});

export const JobModel = mongoose.models.Job || mongoose.model('Job', JobSchema);
